<?php

namespace AppBundle\Repository;

/**
 * YoutubeChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeChannelRepository extends \Doctrine\ORM\EntityRepository
{
}
